export const PACKAGE_STATUS_CREATED = 1
export const PACKAGE_STATUS_PENDING_PICKUP = 2
export const PACKAGE_STATUS_PICKED = 10
export const PACKAGE_STATUS_WAREHOUSE_LABELED = 11
export const PACKAGE_STATUS_WAREHOUSE_INCONTAINER = 12
export const PACKAGE_STATUS_WAREHOUSE_INSHIPMENT = 13
export const PACKAGE_STATUS_WAREHOUSE_EXPORT = 14
export const PACKAGE_STATUS_INTRANSIT = 30
export const PACKAGE_STATUS_DELIVERED = 31
export const PACKAGE_STATUS_RETURNED = 40
export const PACKAGE_STATUS_CANCELLED = 50

export const PACKAGE_STATUS_PROCESSING = [
  PACKAGE_STATUS_PICKED,
  PACKAGE_STATUS_WAREHOUSE_LABELED,
  PACKAGE_STATUS_WAREHOUSE_INCONTAINER,
  PACKAGE_STATUS_WAREHOUSE_INSHIPMENT,
  PACKAGE_STATUS_WAREHOUSE_EXPORT,
]

export const MAP_PACKAGE_STATUS_TEXT = {
  PACKAGE_STATUS_CREATED: 'tạo mới',
  PACKAGE_STATUS_PENDING_PICKUP: 'chờ lấy',
  PACKAGE_STATUS_PICKED: 'đang xử lý',
  PACKAGE_STATUS_WAREHOUSE_LABELED: 'đang xử lý',
  PACKAGE_STATUS_WAREHOUSE_INCONTAINER: 'đang xử lý',
  PACKAGE_STATUS_WAREHOUSE_INSHIPMENT: 'đang xử lý',
  PACKAGE_STATUS_WAREHOUSE_EXPORT: 'đang xử lý',
  PACKAGE_STATUS_INTRANSIT: 'đang giao',
  PACKAGE_STATUS_DELIVERED: 'giao thành công',
  PACKAGE_STATUS_RETURNED: 'trả hàng',
  PACKAGE_STATUS_CANCELLED: 'đã huỷ',
}
