export const ONE_SECOND_MILLISECONDS = 1000
export const ONE_MINUTE_SECONDS = 60
export const ONE_HOUR_SECONDS = 60 * ONE_MINUTE_SECONDS
export const ONE_MINUTE_MILLISECONDS = ONE_SECOND_MILLISECONDS * 60
export const ONE_DAY_SECONDS = 24 * ONE_HOUR_SECONDS
export const ONE_MONTH_SECONDS = 30 * ONE_DAY_SECONDS
export const ONE_DAY_MILISECOND = 24 * 60 * 60 * 1000
export const ONE_HOUR_MILISECOND = ONE_MINUTE_MILLISECONDS * 60

export const VIEW_DATE_FORMAT = 'MMM D, YYYY'
