export const PAGE_VIEW = 'page_view'
export const USER_SIGNUP = 'user_signup'
export const BASE_PRODUCT_CREATE = 'base_product_create'
export const PRODUCT_DELETE = 'product_delete'
export const PRODUCT_CSV_IMPORT = 'product_csv_import'
export const COLLECTION_CREATE = 'collection_create'
export const MANUAL_DISCOUNT_CREATE = 'manual_discount_create'
export const AUTOMATIC_DISCOUNT_CREATE = 'automatic_discount_create'
export const DISCOUNT_DELETE = 'discount_delete'
export const CUSTOMER_ADD = 'customer_add'
export const CUSTOMER_IMPORT = 'customer_import'
export const CUSTOMER_DELETE = 'customer_delete'
export const APP_INSTALL = 'app_install'
export const APP_UNINSTALL = 'app_uninstall'
export const APP_CANCEL_INSTALL = 'app_cancel_install'
export const THEME_PUBLISH = 'theme_publish'
export const THEME_REMOVE = 'theme_remove'
export const THEME_CUSTOMIZE = 'theme_customize'
export const DOMAIN_CLICK_CONNECT = 'domain_click_connect'
export const DOMAIN_ENTER_URL = 'domain_enter_url'
export const DOMAIN_VERIFY_FAIL = 'domain_verify_fail'
export const DOMAIN_CONNECTED = 'domain_connected'
export const PASSWORD_PROTECTION_DISABLE = 'password_protection_disable'
export const GOOGLEANALYTIC_ACCOUNT_CONNECT = 'googleAnalytic_Account_connect'
export const FACEBOOKPIXEL_ID_CONNECT = 'facebookPixel_Id_connect'
export const STAFF_ACCOUNT_ADD = 'staff_account_add'
export const STAFF_ACCOUNT_DELETE = 'staff_account_delete'
export const PAYMENT_PROVIDER_CREDIT_CARD_CONNECTED =
  'payment_provider_credit_card_connected'
export const PAYMENT_PROVIDER_PAYPAL_CONNECTED =
  'payment_provider_paypal_connected'
export const PAYMENT_PROVIDER_FASTERPAY_CONNECTED =
  'payment_provider_fasterpay_connected'
export const PUBLIC_APP_CREATED = 'public_app_created'
